### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by ghost** [Flo504/TagAPI#1]
hello could you give me an example of how to use?

**Comment by Flowsqy** [comment]
Hello,
This code is very old and now outdated. It basically create and send a team packet, which is the only way to modify the name above the head of player. Now you can do it with Bukkit API directly, without the use of NMS. If you want to do it with packet (Which is, I think, a bad idea), you can take a look at ProtocolLib. 
The link to the wiki to it with the bukkit API : [https://www.spigotmc.org/wiki/making-scoreboard-with-teams-no-flicker/](url)

**Comment by ghost** [comment]
Thanks!
